### ISSUE TITLE
Conan recipe not updated for Conan 2.0

### ISSUE THREAD

**Issue by cfrome77** [open-telemetry/opentelemetry-proto#466]
Hello, I am working to upgrade the conanfile.py for a project from 1.x to 2.0. When I trying to build, I get this error about the `opentelemetry-proto` recipe not being conan 2.0 comaptible. If you are able to update the recipe to be 2.0 compatible that would be great so that I am able to properly compile using conan 2.0.

```
*********************************************************
Recipe 'opentelemetry-proto/0.19.0' seems broken.
It is possible that this recipe is not Conan 2.0 ready
If the recipe comes from ConanCenter check: https://conan.io/cci-v2.html
If it is your recipe, check if it is updated to 2.0
*********************************************************

ImportError: cannot import name 'ConanFile' from 'conans'
```

**Comment by tigrannajaryan** [comment]
It is best to take this to C++ maintainers. I am not sure we have anyone in this repo who knows how to deal with Conan.
